// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjgjvgfiyetapapnovot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qZ2p2Z2ZpeWV0YXBhcG5vdm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODI1ODcsImV4cCI6MjA2OTg1ODU4N30.z8mEX6OjFdjNpQpiTsSsS2EK4IEqhbSgeX01hHiTamg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});